[package]
name = "cargo-odra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive", "cargo"] }
clap-cargo = "0.8.0"
cargo_metadata = "0.6.0"
attohttpc = "0.19.1"
convert_case = "0.5.0"
toml = "0.5.9"
serde = "1.0.137"
serde_derive = "1.0.137"