[package]
authors = ["Jakub Płaskonka kuba@odra.dev", "Krzysztof Pobiarżyn krzysztof@odra.dev", "Maciej Zieliński maciej@odra.dev"]
license = "MIT"
repository = "https://github.com/odradev/cargo-odra"
description = "A cargo utility that helps to create, manage and test your smart contracts written using Odra framework."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
name = "cargo-odra"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive", "cargo"] }
clap-cargo = "0.8.0"
cargo_metadata = "0.6.0"
attohttpc = "0.19.1"
convert_case = "0.5.0"
toml = "0.5.9"
serde = "1.0.137"
serde_derive = "1.0.137"
cargo-generate = "0.15.2"
rm_rf = "0.6.2"
glob = "0.3.0"
url = "2.2.2"
cargo_toml = "0.11.5"
regex = "1.6.0"
prettycli = "0.1.1"
heck = "0.4.0"
chrono = "0.4.20"
comfy-table = "6.0.0"