name: ci-cargo-odra

on:
  push:
    branches:
      - master
      - develop
      - release/*
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - release/*
    paths-ignore:
      - "**.md"

jobs:
  build_and_test:
    name: Build and test
    runs-on: buildjet-8vcpu-ubuntu-2204 # We use buildjet instead GH's free ubuntu-latest for faster builds
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: make install
      - run: make test-project-generation
