name: ci-cargo-odra

on:
  push:
    branches:
      - master
      - develop
      - release/*
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - release/*
    paths-ignore:
      - "**.md"

jobs:
  build_and_test:
    name: Build and test
    runs-on: buildjet-32vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout
      - uses: actions-rs/toolchain
        with:
          toolchain: nightly
      - run: make install
      - run: make test-project-generation
